.PHONY: build

build:
	npx cmake-js build --runtime=electron --runtime-version=36.2.1 -p2

reload:
	npx cmake-js configure --runtime=electron --runtime-version=36.2.1

clean:
	npx cmake-js clean --runtime=electron --runtime-version=36.2.1
